# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: login_in
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN}}

      - run: docker build -t ghcr.io/h0lonar/nodejs-app:1.0 nodejs/
      - run: docker push  ghcr.io/h0lonar/nodejs-app:1.0

      - run: docker build -t ghcr.io/h0lonar/python_1-app:1.0 python/
      - run: docker push ghcr.io/h0lonar/python_1-app:1.0
   

  deploy: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: login_in
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN}}

      - run: scp -o "StrictHostKeyChecking no" docker-compose.yml ssh 'whywelive-nketemplate-9c7tmxeq1ua#dHrANgm6CiWNYnLbYJ712cTAi56V_uzI@whywelive-nketemplate-9c7tmxeq1ua.ssh.ws-eu107.gitpod.io':/workspace/nke-template
      - run: ssh -o "StrictHostKeyChecking no" 'whywelive-nketemplate-9c7tmxeq1ua@whywelive-nketemplate-9c7tmxeq1ua.ssh.ws-eu107.gitpod.io' "cd /workspace/nke-template && docker compose pull && docker-compose up -d"
      
